[project]
name = "datamagpie"
version = "0.1.0"
description = "A command-line toolkit for downloading data from biomedical data sources"
readme = "README.md"
authors = [
    { name = "Slade Matthews", email = "53508159+sladem-tox@users.noreply.github.com" }
]
requires-python = ">=3.12"
dependencies = [
    "chembl-webresource-client>=0.10.9",
    "pandas>=2.2.0",
]

[project.optional-dependencies]
tdc = [
    "PyTDC>=1.1.14",
]

[project.scripts]
datamagpie = "datamagpie.cli:main"

[build-system]
requires = ["uv_build>=0.12.15,<0.13.0"]
build-backend = "uv_build"
